name: Unit Tests

on:
  push:
    branches:
      - dev
    paths:
      - 'package.json'
      - '**/*.js'
      - '**/*.mjs'
      
  pull_request:
    types: [ opened ]
    branches:
      - main
    paths:
      - 'package.json'
      - '**/*.js'
      - '**/*.mjs'

env:
  HA_EMAIL: ${{secrets.HA_EMAIL}}
  HA_PASS: ${{secrets.HA_PASS}}

jobs:
  test:
    name: Run Mocha Tests
    runs-on: ubuntu-latest

    container: 
      image: node:18-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

