name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest

    container: 
      image: node:18-alpine

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Set up npm authentication
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use the npm token stored in GitHub secrets
        run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc

      - name: Install Dependencies
        run: npm publish --access public
        